# @domain=https://api-it4u.herokuapp.com/api/v1
@domain=http://localhost:5000/api/v1

POST {{domain}}/role
Content-Type: application/json

{
    "name": "ROLE_ADMIN"
}

###

GET {{domain}}/role
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjU0NTA2NDcxLCJleHAiOjE2NTUxMTEyNzF9.3T-IH7NHaUarPRjcbQfskheEkBxHfOIJgpxBD5HhhL9FuakDcWRt6gYCODPRpjD0eB9XoXiZ_FnlqLkiKt22ww

###

POST {{domain}}/auth/signup
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjU0MTM3NTg1LCJleHAiOjE2NTQ3NDIzODV9.7aUfRUzendQr3s5lJxIAY8jEyYaBYLVYi5TEruvpnkclF1eSqhGve-eF-Y5QkMTQpXpuazmwenvP64W4NNxHCQ
Content-Type: application/json

{
    "name": "Lap Dang",
    "username": "toantran",
    "email": "toan.tran@tpsc.vn",
    "password": "Tpsc.vn@123",
    "gender": "Male",
    "type": "User",
    "sitename": "rhnl7chn"
}
###

GET {{domain}}/user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjU0MzQ5Nzc2LCJleHAiOjE2NTQ5NTQ1NzZ9._hvvW6cpjUs_vEdtChr1R-bG2igVxZ1rJtdAa7fTKo98Qg7HtyvXY4zJtHPzcWqcMP-jUtW9vVvpVp8FUu8Emg

###
POST {{domain}}/auth/signin
Content-Type: application/json

{
    "usernameOrEmail": "admin",
    "password": "Tpsc.vn@123",
    "remember": true
}

###
POST {{domain}}/auth/signin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjU0MDUwNTc5LCJleHAiOjE2NTQ2NTUzNzl9.WGvVAA3ID3QxQ3YZrTIqmPBvBl3E5h05z2DXHklYMtO6bZAbsT7tNzwREsIIWy_rLbWSmrQFpZifp8DQIXaCEw
Content-Type: application/json

{
    "usernameOrEmail": "lapdang",
    "password": "123456"
}

###

GET {{domain}}/user/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjU0NTA2NDcxLCJleHAiOjE2NTUxMTEyNzF9.3T-IH7NHaUarPRjcbQfskheEkBxHfOIJgpxBD5HhhL9FuakDcWRt6gYCODPRpjD0eB9XoXiZ_FnlqLkiKt22ww

###

PUT {{domain}}/user/update
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNTc3ODc3Mzk3LCJleHAiOjE1Nzg0ODIxOTd9.r64sw38PXdDJZadR_AqLqmGpqgcTFDVnOU8IMToM54pKc1gxDfdOJHEq3c00jbLaSxcb_4e09F3tZUP-A_z6Ng
Content-Type: application/json

{
    "name": "Lap Dang",
    "username": "lapdang2",
    "email": "email27@yahoo.com",
    //"password": "123456",
    "gender": "Male",
    "type": "User"
}

###

PUT {{domain}}/user/changePassword
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjU0MTM5MzAxLCJleHAiOjE2NTQ3NDQxMDF9.HcPLxrhTpF2JM1s7f7A8N64HC3XeCOzQV6-1Oy_dIoLLn29Gvv7BYMJRaYxoArp-e8O2sjtpSc0iGujj-uuUCg
Content-Type: application/json

{
    "currentPassword": "123456",
    "newPassword": "Tpsc.vn@123",
    "confirmPassword": "Tpsc.vn@123"
}
###
DELETE {{domain}}/users/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc1OTY3MDg4LCJleHAiOjE1NzY1NzE4ODh9.hR5gDm_vVyuPyM99WSilHBsipLrid-G9foL-ZvEh784xN-B6KbN51cQWOQ4PBwzO2BSvzdUpFmE-vjSwTgkzmA

###
GET {{domain}}/users/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc1OTY3MDg4LCJleHAiOjE1NzY1NzE4ODh9.hR5gDm_vVyuPyM99WSilHBsipLrid-G9foL-ZvEh784xN-B6KbN51cQWOQ4PBwzO2BSvzdUpFmE-vjSwTgkzmA

###
PUT {{domain}}/users/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

{
    "name": "Lap Dang",
    "username": "lapdang",
    "email": "email28@yahoo.com",
    //"password": "123456",
    "gender": "Male",
    "type": "User"
}

###
GET {{domain}}/it4u/sites
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

###
GET {{domain}}/it4u/ljzf8x9r/apCount
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

###
GET {{domain}}/it4u/ljzf8x9r/clientEssid
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

###
GET {{domain}}/it4u/rhnl7chn/clientUsage
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

###
GET {{domain}}/it4u/rhnl7chn/trafficUsage
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

###
GET {{domain}}/it4u/rhnl7chn/radioType
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

###
GET {{domain}}/it4u/rhnl7chn/quickLook
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

###
POST {{domain}}/it4u/1px5g676/5MinutesClient
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

{
    "attrs":["wlan_bytes","wlan-num_sta","time"],
    "start":"1578157200000",
    "end":"1578416400000"
}

###
POST {{domain}}/it4u/1px5g676/dailyClient
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

{
    "attrs":["wlan_bytes","wlan-num_sta","time"],
    "start":"1575219402448",
    "end":"1577811402448"
}

###
POST {{domain}}/it4u/rhnl7chn/dailyAP
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

{
    "attrs":["bytes","num_sta","time"],
    "start":"1578157200000",
    "end":"1578416400000",
    "mac":"18:e8:29:cc:62:67"
}

###
POST {{domain}}/it4u/rhnl7chn/hourlyAP
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

{
    "attrs":["bytes","num_sta","time"],
    "start":"1578157200000",
    "end":"1578416400000",
    "mac":"18:e8:29:cc:62:67"
}

###
POST {{domain}}/it4u/rhnl7chn/5MinutesAP
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

{
    "attrs":["bytes","num_sta","time"],
    "start":"1578157200000",
    "end":"1578416400000",
    "mac":"18:e8:29:cc:62:67"
}

###
POST {{domain}}/it4u/8pcpfwkw/getTimeDaily
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

{
    "attrs":["wlan_bytes","wlan-num_sta","time"],
    "start":"1577898000000",
    "end":"1578103714173"
}

###
POST {{domain}}/it4u/rhnl7chn/getTimeHourly
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

{
    "attrs":["wlan_bytes","wlan-num_sta","time"],
    "start":"1577898000000",
    "end":"1578103714173"
}

###
POST {{domain}}/it4u/rhnl7chn/hourlyClient
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

{
    "attrs":["wlan_bytes","wlan-num_sta","time"],
    "start":"1577898000000",
    "end":"1578103714173"
}

###
POST {{domain}}/it4u/8pcpfwkw/getTimeMinute
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

{
    "attrs":["wlan_bytes","wlan-num_sta","time"],
    "start":"1575219402448",
    "end":"1577811402448"
}

###
GET {{domain}}/it4u/rhnl7chn/hotspot/1575504000000/1578182400000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

###
POST {{domain}}/it4u/rhnl7chn/createVoucher
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

{"cmd":"create-voucher","n":1,"quota":1,"expire":480,"expire_number":1,"expire_unit":1440,
"down":150,"up":150,"bytes":1,"note":"Note Ok"}

###
GET {{domain}}/it4u/rhnl7chn/voucher
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

###
POST  {{domain}}/it4u/rhnl7chn/deleteVoucher
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

{
    "_id":"5e11792be4b0bd372d21a000",
    "cmd":"delete-voucher"
}

###
GET  {{domain}}/it4u/rhnl7chn/printVoucher/5e11792be4b0bd372d21a000
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

###
GET  {{domain}}/it4u/rhnl7chn/getMacAp
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

###
GET  {{domain}}/it4u/49lqd/customerInfo
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json

###
GET  {{domain}}/it4u/rhnl7chn/trafficInfo
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc4NTU5NzY2LCJleHAiOjE1NzkxNjQ1NjZ9.QbyTtKWwfz5lsm0H0SLyhzeY5yS-GoLOI6f_I7iAx94A6wcDujzpMbrWtKwgf2jbRL0KpU8yudz5tUBiLbQ2wQ
Content-Type: application/json
