# @domain=https://api-it4u.herokuapp.com/api/v1
@domain=http://localhost:5000/api/v1
@token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjU5MTU0MDI0LCJleHAiOjE2NTkxNTQ5MjR9.D0UB3Ly2nmonEbldn1iNu5esesxeGAfsw1tpDSilCkLlqqcjg_v_zzKWdGhuadVFwN9hDAINUyEgNNmz6PdM3Q
@refreshToken=ad6004a2-f27f-4aed-910a-536b04b87d61

POST {{domain}}/auth/signin
Content-Type: application/json

{
    "usernameOrEmail": "admin",
    "password": "Tpsc.vn@123",
    "remember": true
}

###

GET {{domain}}/user/me
Authorization: Bearer {{token}}

###

GET {{domain}}/user
Authorization: Bearer {{token}}

###

POST {{domain}}/auth/signup
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Toan Tran",
    "username": "toan1",
    "email": "toan1@tpsc.vn",
    "password": "123456",
    "type": "USER",
    "sitename": ["1px5g676", "rhnl7chn"],
    "roles": "ROLE_USER"
}

###

POST {{domain}}/auth/addSitename
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "KH4322",
    "username": "KH4232",
    "email": "lap.dang7@tpsc.vn",
    "password": "123456",
    "sitename": "vr5hy29h"
}

###
POST {{domain}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

###
POST {{domain}}/auth/logout
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "userId": "1"
}

###

PUT {{domain}}/user/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "admin1"
}

###

PUT {{domain}}/user/changePassword
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "currentPassword": "123456",
    "newPassword": "Tpsc.vn@123",
    "confirmPassword": "Tpsc.vn@123"
}
###
DELETE {{domain}}/users/3
Authorization: Bearer {{token}}

###
GET {{domain}}/users/2
Authorization: Bearer {{token}}

###
PUT {{domain}}/users/2
Authorization: Bearer {{token}}

###
PUT {/changePassword/11
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "newPassword": "123456",
    "confirmPassword": "123456"
}