# app config

app:
  api:
    version: /api/v1
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
  
  ubnt:
    url: https://ubnt.cloud.tpsc.vn/api
    username: lap.dang@tpsc.vn
    password: Nccvbcl0167@
    csrf_token: NBxvz8e7iSf89xYSeDL2kXMq1QzlO3l6
    unifises: 5TQPI1uboHRVFXg88OuNMEvE1E9ukx1Y
  dev:
    url: https://dev.tpsc.vn/api/customer_info
    token: 15cadd25-ee0c-40b2-bdff-0ce622298336
  zabbix:
    url: http://172.16.10.244
    username: Admin
    password: zabbix
    token: b8a9ec9e9722d39e5d97b1c1c9555bbd
spring:
  profiles:
    active: prod

  # Jackson Properties
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  
  #locale
  messages:
    basename: i18n/errors,i18n/messages
