## Server Properties
server:
  port: ${SERVER_PORT}

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    # initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    generate-ddl: true
    hibernate:  
      ddl-auto: update  
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #     jdbc.lob.non_contextual_creation: true