# app config
app:
  api:
    version: /api/v1
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

spring:
  profiles:
    active: dev

  # Jackson Properties
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

  # Database config  
  jpa:
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate.ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  
  #locale
  messages:
    basename: i18n/errors,i18n/messages
