## Server Properties
server:
  port: 5000

logging:
  file:
    name: log.txt
    path: ./
  level:
  #   root: WARN
  #   org.springframework.web: DEBUG
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace

    # org.hibernate: DEBUG

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    # initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/it4uPG
    username: it4u
    password: 123456
    platform: postgresql
    data: data.sql
    initialization-mode: always
    continue-on-error: true

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    generate-ddl: true
    hibernate:  
      ddl-auto: none  
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        format_sql: true