# app config

app:
  api:
    version: /api/v1
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
  
  ubnt:
    url: https://ubnt.cloud.tpsc.vn/api
    username: lap.dang@tpsc.vn
    password: Nccvbcl0167@
    csrf_token: MVg26a6xen92xxokOqw3yw88Y1o3zB8N
    unifises: Z9ZDuk2z6rfXQnxnzAqtkAVEJhAPt9cI
  dev:
    url: https://dev.tpsc.vn/api/customer_info
    token: 15cadd25-ee0c-40b2-bdff-0ce622298336
  zabbix:
    url: https://monitor.tpsc.vn
    username: Zabbix
    password: Tpsc.vn@123
    token: d756ebaf696799ad90ea118e68301351
spring:
  profiles:
    active: prod

  # Jackson Properties
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  
  #locale
  messages:
    basename: i18n/errors,i18n/messages
