# app config

app:
  api:
    version: /api/v1
  jwtSecret: ${JWT_SECRET_KEY:JWTSuperSecretKey}
  jwtExpirationInMs: ${JWT_EXPIRATION:604800000}
  cors.allowedOrigins: '*'

  ubnt:
    url: https://ubnt.cloud.tpsc.vn/api
    csrf_token: dOF18vvMYAVy7Ck7zFqC3ZRQ22x1V5YM
    unifises: q6o8WVSRigOPv9RsLelFxkYzpSa2J2ZS
  dev:
    url: https://dev.tpsc.vn/api/customer_info
    token: 15cadd25-ee0c-40b2-bdff-0ce622298336
spring:
  profiles:
    active: dev

  datasource:
    driverClassName: ${DATABASE_DRIVER:}
    # url: jdbc:h2:file:F:/Dev/TPs/it4u/it4u-server
    url: ${DATABASE_URL:}
    username: ${DATABASE_USER:}
    password: ${DATABASE_PASSWORD:}

  jpa:
    show-sql: true
    generate-ddl: false
    # Disable Hibernate automatic schema creation:
    # hibernate.ddl-auto: none
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:}
        '[use_sql_comments]': true
        '[format_sql]': true
        jdbc:
          lob:
            '[non_contextual_creation]': true

  sql:
    init:
      data-locations:
        - classpath:db\changelog\data.sql
      mode: always
      continue-on-error: true
  # Jackson Properties
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

  #locale
  messages:
    basename: i18n/errors,i18n/messages

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  # flyway:
  #   enabled: false
  #   locations:
  #   - classpath:db/migration/{vendor}
# ---
# spring:
#   profiles: generatesql
#   flyway:
#     enabled: false
#   jpa:
#     properties:
#       javax:
#         persistence:
#           schema-generation:
#             create-source: metadata
#             scripts:
#               action: create
#               create-target: src/main/resources/db/ddl_jpa_creation.sql
