# app config

app:
  api:
    version: /api/v1
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
  
  ubnt:
    url: https://ubnt.cloud.tpsc.vn/api
    username: lap.dang@tpsc.vn
    password: Nccvbcl0167@
    csrf_token: pNoTDSHx71LwSrLFDCWAoWU6HmmAZOns
    unifises: dpYFtZCjDDjvhjPWLZXtpBibn5cXG3vr
  dev:
    url: https://dev.tpsc.vn/api/customer_info
    token: 15cadd25-ee0c-40b2-bdff-0ce622298336
spring:
  profiles:
    active: prod

  # Jackson Properties
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  
  #locale
  messages:
    basename: i18n/errors,i18n/messages
