## Server Properties
server:
  port: 5000

spring:  
  h2.console.enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:F:/Dev/Test/poll-app/poll-server
    username: sa
    password:    
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
