## Server Properties
server:
  port: 5000
# debug: true

# logging:
#   file:
#     name: log.txt
#     path: ./
#   level:
#   #   root: WARN
#   #   org.springframework.web: DEBUG
#     org:
#       hibernate:
#         SQL: debug
#         type.descriptor.sql: trace

# org.hibernate: DEBUG

# spring:
#   h2:
#     console:
#       enabled: true
#       settings:
#         web-allow-others: true
#   datasource:
#     driverClassName: org.h2.Driver
#     # url: jdbc:h2:file:F:/Dev/TPs/it4u/it4u-server
#     url: jdbc:h2:mem:it4uDb
#     username: sa
#     password:
#   jpa:
#     show-sql: true
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.H2Dialect
#         # show-sql: true
#         use_sql_comments: true
#         format_sql: true
# springdoc:
#   api-docs:
#     path: /api-docs

spring:
  datasource:
    # initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.36.129:5433/it4uDb
    username: it4u
    password: 123456

  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
